extends:
  - eslint:recommended
  - airbnb-base

env:
  es6: false

globals:
  aster: true

parserOptions:
  sourceType: script

rules:
  # Possible Errors
  no-console: off

  # Best Practices
  vars-on-top: off

  # Strict Mode
  strict:
    - error
    - global

  # Stylistic Issues
  no-bitwise: off
  no-plusplus: off
  no-underscore-dangle: off

  # ECMAScript 6
  no-var: off
  object-shorthand: off
  prefer-rest-params: off
  prefer-template: off

  # plugin: import
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
