extends:
  - eslint:recommended
  - airbnb-base

env:
  es6: false

globals:
  aster: true

parserOptions:
  sourceType: script

rules:
  # Possible Errors
  no-console: off

  # Best Practices
  no-param-reassign: off
  vars-on-top: off
  yoda: off

  # Strict Mode
  strict:
    - error
    - global

  # Stylistic Issues
  func-names: off
  no-bitwise: off
  no-multi-assign: off
  no-nested-ternary: off
  no-plusplus: off
  no-underscore-dangle: off
  space-before-function-paren:
    - error
    - never

  # ECMAScript 6
  no-var: off
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-destructuring: off
  prefer-rest-params: off
  prefer-spread: off
  prefer-template: off

  # plugin: import
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
