[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  branch = "master"

[[constraint]]
  name = "github.com/hattya/go.binfmt"
  branch = "master"

[[constraint]]
  name = "github.com/hattya/go.cli"
  branch = "master"

[[constraint]]
  name = "github.com/hattya/go.notify"
  branch = "master"

[[constraint]]
  name = "github.com/robertkrimen/otto"
  branch = "master"
